services:
  nginx:
    image: cherkasik/rdga-nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt/
    depends_on:
      - web
      - backend
      - database
    networks:
      - backbone
    restart: always

  web:
    image: cherkasik/rdga-web
    container_name: web
    expose:
      - 80
    networks:
      - backbone
    restart: always

  backend:
    image: cherkasik/rdga-backend
    container_name: backend
    expose:
      - 8080
    volumes:
      - logs:/app/logs
    depends_on:
      - database
    networks:
      - backbone
    restart: always

  database:
    image: cherkasik/rdga-database
    container_name: database
    expose:
      - 5432
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - backbone
    restart: always

volumes:
  database-data:
    driver: local
    name: 'db-volume'
  logs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/root/logs'
    name: 'logs-volume'

networks:
  backbone:
    driver: bridge
